### ISSUE TITLE
function calls with string parameter by value

### ISSUE THREAD

**Issue by Gundolf68** [JamesBoer/Jinx#14]
It seems that strings in a function call are passed by value:
```
import core

function test {str}
    set str[1] to "x"
end

set s to "Hello"
test s
write line s -- prints "Hello" unchanged
```
Is this intentional since strings are now mutable?
If so, wouldn't it make more sense (and be more consistent) to pass strings like collections by reference?
From the programmer's point of view, a string would then be a collection of strings.
This also applies to iterating over strings with "over".

**Comment by JamesBoer** [comment]
Strings are still immutable.  What occurs with string operations is that the string is replaced when modified (similar to C#).  This has some advantages, such as being able to insert entire strings, as well as correctly accounting for multi-byte Unicode characters of different sizes.  In-place character modification would not be able to do that.

Internally, since variables hold strings by value, functions are going to pass them by value as well.  The only reason collections or buffers are passed by reference is that, internally, they are represented by pointers, not by value.  So, it would be a considerable amount of work to special case passing strings by reference, and I'm not sure the advantages would be worth the trouble.

Iterating over strings seems like a reasonable idea, so I'll look into how difficult this would be to add.

**Comment by Gundolf68** [comment]
Ok. Thanks for the explanation.
