### ISSUE TITLE
enum and strings

### ISSUE THREAD

**Issue by brjoha** [JamesBoer/Jinx#18]
Hello again.

Am doing a bit of integration to kick the tires and am wondering if there is a good way to handle enum mapping?  From what I can tell, casting to/from a jinx integer seems to be the only option, which creates a safety exposure when casting back to the native enum.

Was also wondering about jinx strings.  It seems operations are limited to reading and overwriting a given index.  Not looking for the rich set of algorithms and manipulation that C++ allows, but, as a suggestion, at least the basics that C allows?

**Comment by JamesBoer** [comment]
You're correct that Jinx only supports integers, not enums.  It does support read-only properties, which could be mapped to enum values, but there's no built in type..  I'd have to give some thought about the best way to handle this in a way that makes sense.

Regarding strings, you're correct that Jinx has only a few basic string functions at the moment.  This is largely because I never needed anything beyond basic conversion functions (all types can easily convert to and from strings.).  The core library is admittedly pretty minimal, but if you find you have need of particular functionality that's currently not available, just let me know and I'd be happy to consider adding that functionality.  In the meantime, any missing functionality could likely be covered by adding library functions.  The same interface that the core library uses is available to users to create their own libraries.

I've added fairly significant functionality in the past at user requests (first-class functions and coroutines), so I'm certainly not opposed to doing so.  I'd just like to make sure there's a firm need before doing the work.

**Comment by brjoha** [comment]
That's true, a library of C-like string functions would work well enough.

Agree that enum mapping will be tricky to support.  C++23 Reflection TS would likely help here.  Perhaps a scaled down Jinx specific version?

**Comment by JamesBoer** [comment]
Yeah, I've seen some of those types of enum libraries, but I'm really not keen on adding other third-party dependencies.  As you indicated, that sort of thing will be a lot easier when reflection is part of C++.

If I were to add enum support, it would probably be in the form of a new variant type.  You'd still have to cast from the numeric value to the C++ enum, but at least there would be guarantees that the values are always properly mapped to the C++ type.
