### ISSUE TITLE
Precedence in Documentation

### ISSUE THREAD

**Issue by SirNate0** [JamesBoer/Jinx#22]
Looking through the documentaiton, I saw this line, but I think it is inverted:

> Mathematical and logical expressions have a lower precedence than functions, and so are always evaluated before the function call is executed. 

Shouldn't it be that the mathematical/logical expressions have *higher* precedence, since they are evaluated first.

https://stackoverflow.com/questions/18117353/what-does-higher-precedence-mean

**Comment by JamesBoer** [comment]
Yeah, I think you're correct.  I'm not sure why I specified that backwards.  Thanks for letting me know.

**Comment by SirNate0** [comment]
I think you probably wrote it that way because your code uses smaller values for higher precedence https://github.com/JamesBoer/Jinx/blob/f2280a751993a08870bad12d51995e9ab842adf6/Source/JxParser.cpp#L168-L189

I still think the documentation should be updated to reflect the typical usage of the word. Maybe the code as well to use higher values for higher precedence, but that one is not unprecedented (and we can just view it as being similar to 1st priority, 2nd priority, etc. rather than value=1, value=2, etc.).

**Comment by JamesBoer** [comment]
Perhaps I used the C++ documentation as a reference, which uses lower numbers as higher precedence as well.  https://en.cppreference.com/w/cpp/language/operator_precedence

But I did a quick check, and it seems like other references to precedence are correct, indicating higher precedence is executed first.  So it looks like it was just a one-off error.  I wrote this a while ago, so it's a bit hard to remember.  Anyhow, I'll get the documentation updated.  I think I'll leave the code alone, since it's internal and functioning correctly, and as you say, those values could be seen as "priority".  Or maybe I'll just add a quick comment.
