### ISSUE TITLE
The certificate for www.jinx-lang.org has expired

### ISSUE THREAD

**Issue by jamestmartin** [JamesBoer/Jinx#7]
https://www.jinx-lang.org/ now presents a security error when I attempt to connect. Apparently it expired on January 15th.

**Comment by JamesBoer** [comment]
Thanks for letting me know.  My provider didn’t automatically install the new certificate I ordered for some reason, and I didn’t check back for a while.  I’m in the process of getting that installed now, so hopefully will be fixed in the next day or two.  From: James MartinSent: Tuesday, February 25, 2020 7:49 PMTo: JamesBoer/JinxCc: SubscribedSubject: [JamesBoer/Jinx] The certificate for www.jinx-lang.org has expired (#7) https://www.jinx-lang.org/ now presents a security error when I attempt to connect. Apparently it expired on January 12th.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jamestmartin** [comment]
Alright. Just FYI, you might want to check how your email reply came across on the GitHub website, because it's filled with garbage text.

**Comment by JamesBoer** [comment]
Wow, you're right.  That's pretty annoying.  I guess replying to the e-mail directly in Windows Mail isn't a good idea.
